### ISSUE TITLE
isUrl often returns false negatives

### ISSUE THREAD

**Issue by ghost** [eMerzh/PasteMiddleAndGo#1]
Hi, I don't know if you're still maintaining this but it's a nice add-on.

Here's a valid URL it doesn't recognise (the trailing slash is what breaks it): `http://example.com/`

I propose changing the regex in isUrl to something like this, seems to work much better:

```
v.compile(/^\s*(([a-zA-Z-]{2,6}):\/\/)?([a-zA-Z0-9-]+\.)+?([a-zA-Z-]{2,6})(:\d{2,5})?(\/\S*)?\s*$/);
```

**Comment by fraff** [comment]
I agree, the default regex won't grep i.imgur.com.

**Comment by eMerzh** [comment]
Oups ... i didn't saw this coming .... i'll try to fix it tonight ...

thanks a lot @flussence  for the regexp :)
